{
 "title": "Kubernetes Cluster Alarms",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Worker Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{id=\"/\"} / scalar(min(machine_memory_bytes)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate (container_cpu_usage_seconds_total{id=\"/\"}[5m])) by (instance)) / scalar(sum (machine_cpu_cores)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace != \"kube-system\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace != \"kube-system\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Container-specific file system usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.{1,2}da.?$\",id=\"/\"}) by (instance) / sum (container_fs_limit_bytes{device=~\"^/dev/.{1,2}da.?$\",id=\"/\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Nodes Unavailable",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"false\"})"
    }
   ]
  },
  {
   "title": "Cluster Cores Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores) - sum(kube_pod_container_resource_requests_cpu_cores)"
    }
   ]
  },
  {
   "title": "Most Node Cores Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max((sum(kube_node_status_allocatable_cpu_cores) by (node)) - (sum(kube_pod_container_resource_requests_cpu_cores) by (node)))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total Cluster Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes) - sum(kube_pod_container_resource_requests_memory_bytes)"
    }
   ]
  },
  {
   "title": "Max Node Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max((sum(kube_node_status_allocatable_memory_bytes) by (node)) - (sum(kube_pod_container_resource_requests_memory_bytes) by (node)))",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}